-- Tours Table
CREATE TABLE IF NOT EXISTS tours (
  id int(11) NOT NULL AUTO_INCREMENT,
  name_en varchar(255) NOT NULL,
  name_vi varchar(255) NOT NULL,
  description_en text NOT NULL,
  description_vi text NOT NULL,
  full_description_en text NOT NULL,
  full_description_vi text NOT NULL,
  category_en varchar(50) NOT NULL,
  category_vi varchar(50) NOT NULL,
  duration varchar(50) NOT NULL,
  max_people int(11) NOT NULL,
  price_per_person decimal(10,2) NOT NULL,
  meeting_point_en varchar(255) NOT NULL,
  meeting_point_vi varchar(255) NOT NULL,
  includes text NOT NULL,
  image_url varchar(255) NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Insert sample tours data
INSERT INTO tours (name_en, name_vi, description_en, description_vi, full_description_en, full_description_vi, category_en, category_vi, duration, max_people, price_per_person, meeting_point_en, meeting_point_vi, includes, image_url) VALUES
('Island Hopping Adventure', 'Phiêu Lưu Khám Phá Đảo', 'Explore the stunning islands around Nha Trang with our professional guides. Swim, snorkel, and enjoy fresh seafood lunch.', 'Khám phá những hòn đảo tuyệt đẹp quanh Nha Trang với đội ngũ hướng dẫn viên chuyên nghiệp. Bơi, lặn và thưởng thức bữa trưa hải sản tươi ngon.', 'Embark on an unforgettable island-hopping adventure around the stunning Nha Trang Bay. Our experienced guides will take you to multiple islands where you can swim in crystal-clear waters, snorkel among vibrant coral reefs, and discover the diverse marine life. Enjoy a delicious seafood lunch prepared fresh on one of the islands. This tour is perfect for nature lovers and adventure seekers who want to experience the natural beauty of Vietnam\'s coastline. All necessary equipment is provided, and no prior snorkeling experience is required.', 'Bắt đầu chuyến phiêu lưu khám phá đảo không thể quên quanh Vịnh Nha Trang tuyệt đẹp. Các hướng dẫn viên giàu kinh nghiệm của chúng tôi sẽ đưa bạn đến nhiều hòn đảo, nơi bạn có thể bơi trong làn nước trong vắt, lặn ngắm san hô rực rỡ và khám phá đa dạng sinh vật biển. Thưởng thức bữa trưa hải sản ngon tuyệt được chế biến tươi ngon trên một trong những hòn đảo. Tour này hoàn hảo cho những người yêu thiên nhiên và những người tìm kiếm phiêu lưu muốn trải nghiệm vẻ đẹp tự nhiên của bờ biển Việt Nam. Tất cả các thiết bị cần thiết đều được cung cấp và không cần kinh nghiệm lặn trước đó.', 'Adventure', 'Phiêu Lưu', '8 hours', 12, 89.00, 'Resort Lobby', 'Sảnh Resort', 'Boat ride, Snorkeling gear, Lunch, Drinks', 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1950&q=80'),
('City Cultural Tour', 'Tour Văn Hóa Thành Phố', 'Discover Nha Trang\'s cultural heritage with visits to ancient temples, historic sites, and local craft villages.', 'Khám phá di sản văn hóa của Nha Trang với các chuyến thăm đến đền chùa cổ, các di tích lịch sử và làng nghề thủ công.', 'Immerse yourself in the rich cultural heritage of Nha Trang with our comprehensive city tour. Visit ancient Cham temples that date back centuries, explore historical landmarks that tell the story of Vietnam\'s past, and experience the authentic lifestyle in local craft villages. Our knowledgeable guides will share fascinating insights about the region\'s history, traditions, and customs. You\'ll also have the opportunity to interact with local artisans and learn about traditional crafts. The tour includes a delicious authentic Vietnamese lunch at a local restaurant, giving you a taste of the region\'s culinary delights.', 'Đắm mình trong di sản văn hóa phong phú của Nha Trang với tour thành phố toàn diện của chúng tôi. Thăm các đền thờ Chăm cổ có niên đại hàng thế kỷ, khám phá các địa danh lịch sử kể câu chuyện về quá khứ của Việt Nam và trải nghiệm lối sống đích thực tại các làng nghề địa phương. Các hướng dẫn viên am hiểu của chúng tôi sẽ chia sẻ những hiểu biết hấp dẫn về lịch sử, truyền thống và phong tục của vùng. Bạn cũng sẽ có cơ hội tương tác với các nghệ nhân địa phương và tìm hiểu về các nghề thủ công truyền thống. Tour bao gồm bữa trưa đích thực của Việt Nam tại nhà hàng địa phương, mang đến cho bạn hương vị ẩm thực đặc trưng của vùng.', 'Cultural', 'Văn Hóa', '6 hours', 15, 65.00, 'Resort Lobby', 'Sảnh Resort', 'Transportation, Entrance fees, Local guide, Lunch', 'https://images.pexels.com/photos/6143369/pexels-photo-6143369.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'),
('Sunset Sailing Cruise', 'Du Thuyền Hoàng Hôn', 'Enjoy a breathtaking sunset on our luxury catamaran. Includes cocktails, light dinner, and the opportunity to spot marine life.', 'Tận hưởng cảnh hoàng hôn tuyệt đẹp trên du thuyền sang trọng. Bao gồm cocktail, bữa tối nhẹ và cơ hội ngắm nhìn sinh vật biển.', 'Set sail on our luxury catamaran for an unforgettable sunset experience on the waters of Nha Trang Bay. As the sun begins to set, the sky transforms into a canvas of vibrant colors, creating a magical backdrop for your evening cruise. Sip on handcrafted cocktails and enjoy a delicious light dinner featuring local and international cuisine. Our attentive crew will point out marine life such as dolphins and flying fish that often appear during this time. The gentle sound of live acoustic music completes this perfect evening on the water. This cruise is ideal for couples seeking romance, photographers capturing the perfect sunset, or anyone looking to end their day in a truly special way.', 'Khởi hành trên du thuyền sang trọng của chúng tôi để có trải nghiệm hoàng hôn khó quên trên vùng biển Vịnh Nha Trang. Khi mặt trời bắt đầu lặn, bầu trời biến thành một bức tranh với những màu sắc rực rỡ, tạo nên một khung cảnh kỳ diệu cho chuyến du thuyền buổi tối của bạn. Nhâm nhi những ly cocktail thủ công và thưởng thức bữa tối nhẹ nhàng ngon miệng với các món ăn địa phương và quốc tế. Đội thủy thủ chu đáo của chúng tôi sẽ chỉ cho bạn thấy những sinh vật biển như cá heo và cá chuồn thường xuất hiện trong thời gian này. Âm thanh nhẹ nhàng của nhạc acoustic sống hoàn thiện buổi tối hoàn hảo này trên mặt nước. Chuyến du thuyền này lý tưởng cho các cặp đôi tìm kiếm sự lãng mạn, nhiếp ảnh gia ghi lại hoàng hôn hoàn hảo, hoặc bất kỳ ai muốn kết thúc ngày của họ theo một cách thực sự đặc biệt.', 'Relaxation', 'Thư Giãn', '3 hours', 20, 120.00, 'Resort Marina', 'Bến Du Thuyền Resort', 'Luxury catamaran, Cocktails, Dinner, Live music', 'https://images.pexels.com/photos/163236/luxury-yacht-boat-speed-water-163236.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'),
('Countryside Bike Tour', 'Tour Xe Đạp Vùng Quê', 'Cycle through the picturesque countryside of Nha Trang, visit local villages, rice fields, and experience authentic rural life.', 'Đạp xe qua những vùng quê đẹp như tranh của Nha Trang, thăm các làng quê, ruộng lúa và trải nghiệm cuộc sống nông thôn đích thực.', 'Escape the bustling city and discover the serene beauty of Nha Trang\'s countryside on our guided bicycle tour. Pedal through lush landscapes of rice paddies, vegetable farms, and fruit orchards while enjoying the fresh air and stunning mountain views. Visit authentic local villages where you\'ll have the chance to meet friendly locals and learn about their traditional way of life. Stop at a family home to see how rice paper and rice wine are made using age-old techniques. This leisurely-paced tour is suitable for riders of all levels, with plenty of stops for photos, rest, and refreshments. Experience a side of Vietnam that many tourists never see on this immersive cultural adventure.', 'Thoát khỏi thành phố nhộn nhịp và khám phá vẻ đẹp thanh bình của vùng quê Nha Trang trong tour xe đạp có hướng dẫn của chúng tôi. Đạp xe qua những cảnh quan xanh tươi của cánh đồng lúa, trang trại rau và vườn cây ăn quả trong khi tận hưởng không khí trong lành và tầm nhìn núi non tuyệt đẹp. Thăm các làng quê đích thực nơi bạn sẽ có cơ hội gặp gỡ người dân địa phương thân thiện và tìm hiểu về lối sống truyền thống của họ. Dừng chân tại một ngôi nhà gia đình để xem cách làm bánh tráng và rượu gạo bằng kỹ thuật lâu đời. Tour với nhịp độ thong thả này phù hợp với người đi xe đạp ở mọi trình độ, với nhiều điểm dừng để chụp ảnh, nghỉ ngơi và giải khát. Trải nghiệm một khía cạnh của Việt Nam mà nhiều du khách không bao giờ thấy trong cuộc phiêu lưu văn hóa đắm chìm này.', 'Adventure', 'Phiêu Lưu', '5 hours', 10, 55.00, 'Resort Lobby', 'Sảnh Resort', 'Bike rental, Safety gear, Water, Local snacks', 'https://images.pexels.com/photos/100582/pexels-photo-100582.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'),
('Cooking Class & Market Tour', 'Lớp Học Nấu Ăn & Tour Chợ', 'Learn the art of Vietnamese cuisine with a local chef. Visit the market to select fresh ingredients and prepare traditional dishes.', 'Học nghệ thuật ẩm thực Việt Nam với đầu bếp địa phương. Thăm chợ để chọn nguyên liệu tươi và chế biến các món ăn truyền thống.', 'Discover the secrets of Vietnamese cuisine in our hands-on cooking class led by an experienced local chef. The experience begins with a guided tour of a vibrant local market, where you\'ll learn to select the freshest ingredients and discover exotic herbs and spices essential to Vietnamese cooking. Back in our purpose-built cooking school, you\'ll prepare a complete menu of traditional dishes, mastering techniques that have been passed down through generations. Learn to balance the five fundamental flavors that make Vietnamese cuisine so distinctive: sweet, sour, bitter, spicy, and salty. At the end of the class, enjoy the delicious meal you\'ve created in a convivial atmosphere. You\'ll also receive a recipe book so you can recreate these authentic dishes at home and impress your friends and family.', 'Khám phá bí mật của ẩm thực Việt Nam trong lớp học nấu ăn thực hành của chúng tôi dưới sự hướng dẫn của đầu bếp địa phương giàu kinh nghiệm. Trải nghiệm bắt đầu với chuyến tham quan có hướng dẫn đến chợ địa phương sôi động, nơi bạn sẽ học cách chọn nguyên liệu tươi ngon nhất và khám phá các loại thảo mộc và gia vị độc đáo cần thiết cho ẩm thực Việt Nam. Trở lại trường dạy nấu ăn được xây dựng cho mục đích này, bạn sẽ chuẩn bị một thực đơn đầy đủ các món ăn truyền thống, làm chủ các kỹ thuật đã được truyền qua nhiều thế hệ. Học cách cân bằng năm hương vị cơ bản làm nên sự đặc biệt của ẩm thực Việt Nam: ngọt, chua, đắng, cay và mặn. Vào cuối lớp học, thưởng thức bữa ăn ngon bạn đã tạo ra trong không khí thân thiện. Bạn cũng sẽ nhận được một cuốn sách công thức để có thể tái tạo những món ăn đích thực này tại nhà và gây ấn tượng với bạn bè và gia đình.', 'Food', 'Ẩm Thực', '4 hours', 8, 75.00, 'Resort Restaurant', 'Nhà Hàng Resort', 'Market visit, Ingredients, Cooking tools, Recipe book', 'https://images.unsplash.com/photo-1569420067112-b57b4f024595?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1950&q=80'),
('Mud Bath Spa Experience', 'Trải Nghiệm Tắm Bùn Khoáng', 'Relax in the famous Nha Trang mineral mud baths. Includes spa treatments, mineral water swimming, and private relaxation areas.', 'Thư giãn trong các bồn tắm bùn khoáng nổi tiếng của Nha Trang. Bao gồm các liệu pháp spa, bơi nước khoáng và khu thư giãn riêng.', 'Indulge in a rejuvenating spa experience at Nha Trang\'s renowned mineral mud baths. This therapeutic treatment begins with a warm mineral mud bath, rich in natural elements that nourish your skin and relieve muscle tension. The mineral-rich mud is known for its detoxifying properties and ability to improve circulation. After your mud bath, rinse off in a refreshing mineral waterfall before relaxing in a hot mineral water pool. The experience continues with time in a jacuzzi and a professional 30-minute massage focusing on pressure points to release any remaining tension. Throughout your spa journey, you\'ll have access to private relaxation areas where you can unwind with herbal tea and fresh fruit. This wellness experience will leave you feeling completely refreshed and revitalized.', 'Đắm mình trong trải nghiệm spa trẻ hóa tại các bồn tắm bùn khoáng nổi tiếng của Nha Trang. Liệu pháp trị liệu này bắt đầu với bồn tắm bùn khoáng ấm, giàu các nguyên tố tự nhiên nuôi dưỡng làn da và giảm căng thẳng cơ bắp. Bùn giàu khoáng chất được biết đến với đặc tính giải độc và khả năng cải thiện tuần hoàn. Sau khi tắm bùn, rửa sạch dưới thác nước khoáng mát lạnh trước khi thư giãn trong hồ nước khoáng nóng. Trải nghiệm tiếp tục với thời gian trong bồn sục và massage chuyên nghiệp 30 phút tập trung vào các điểm áp lực để giải phóng bất kỳ căng thẳng còn lại. Trong suốt hành trình spa, bạn sẽ có quyền truy cập vào các khu vực thư giãn riêng tư nơi bạn có thể thư giãn với trà thảo mộc và trái cây tươi. Trải nghiệm sức khỏe này sẽ khiến bạn cảm thấy hoàn toàn sảng khoái và tràn đầy sinh lực.', 'Wellness', 'Sức Khỏe', '4 hours', 10, 95.00, 'Resort Spa', 'Spa Resort', 'Mud bath, Hot mineral bath, Jacuzzi, Massage', 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1950&q=80');
